version: '3'
services:
  client:
    build: ./client
    env_file:
      - ./client/.env
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - 3000:3000
    container_name: tgp_client
    depends_on:
      - server
  server:
    build: ./server
    env_file:
      - ./server/.env
    volumes:
      - ./server:/server
      - /server/node_modules
    ports:
      - 5000:5000
      - 9229:9229
    command:
      - nodemon
      - "--inspect-brk=0.0.0.0"
      - "server.js"
    container_name: tgp_server
