version: '3'
services:
  client:
    build: ./client
    env_file:
      - ./client/.env
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - 3000:3000
    container_name: tgp_client
    depends_on:
      - server
  server:
    build: ./server
    env_file:
      - ./server/.env
    volumes:
      - ./server:/server
      - /server/node_modules
    ports:
      - 5000:5000
      - 9229:9229
    command:
      - node
      - "server.js"
    container_name: tgp_server
  scheduler:
    build: ./scheduler
    env_file:
      - ./scheduler/.env
    volumes:
      - ./scheduler:/scheduler
      - /scheduler/node_modules
    command:
      - node
      - "scheduler.js"
    container_name: tgp_scheduler
