version: '3'
services:
  client:
    build: ./client
    environment:
      REACT_APP_AUTH0_DOMAIN: $REACT_APP_AUTH0_DOMAIN
      REACT_APP_AUTH0_CLIENT_ID: $REACT_APP_AUTH0_CLIENT_ID
      REACT_APP_AUTH0_CALLBACK_URL: $REACT_APP_AUTH0_CALLBACK_URL
      REACT_APP_AUTH0_API_URL: $REACT_APP_AUTH0_API_URL
      REACT_APP_API_URL: $REACT_APP_API_URL
      REACT_APP_CLIENT_URL: $REACT_APP_CLIENT_URL
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - 3000:3000
    container_name: tgp_client
    depends_on:
      - server
  server:
    build: ./server
    environment:
      MONGO_URL: $MONGO_URL
      REDIS_URL: $REDIS_URL
      SPORTS_RADAR_URI: $SPORTS_RADAR_URI
      SPORTS_RADAR_API_KEY: $SPORTS_RADAR_API_KEY
      EMAIL_USER: $EMAIL_USER
      EMAIL_PASS: $EMAIL_PASS
      AUTH0_DOMAIN: $AUTH0_DOMAIN
      AUTH0_CLIENT_ID: $AUTH0_CLIENT_ID
    volumes:
      - ./server:/server
      - /server/node_modules
    ports:
      - 5000:5000
      - 9229:9229
    command:
      - node
      - "--inspect=0.0.0.0"
      - "server.js"
    container_name: tgp_server
